import 'dart:math';

import 'package:audioplayers/audioplayers.dart';
import 'package:flutter/foundation.dart';

/// One-shot game sound effects (assets/audio/, generated by scripts/gen_sfx.py).
///
/// Sound must NEVER break gameplay: every play call is fire-and-forget and
/// swallows platform errors (e.g. missing audio focus, or running in a test
/// environment with no plugin). Widget tests get [SilentGameSfx] via DI.
abstract class GameSfx {
  /// Balloon pop. [pitch] lets callers randomize slightly (~0.9–1.15) so a
  /// rapid streak of pops doesn't sound robotic.
  void pop({double pitch = 1.0});

  /// Bomb explosion.
  void boom();

  /// Countdown tick (pre-roll digits + last seconds of the round).
  void tick();

  /// Round-start "GO!".
  void go();

  /// Round-over jingle.
  void fanfare();

  /// A balloon escaping upward.
  void whoosh();
}

class AudioGameSfx implements GameSfx {
  // A small pool so overlapping pops don't cut each other off. lowLatency mode
  // keeps the sample resident for tap-synced playback.
  final List<AudioPlayer> _pool;
  int _next = 0;
  final Random _random = Random();

  AudioGameSfx({int poolSize = 4})
      : _pool = List.generate(poolSize, (_) {
          final p = AudioPlayer();
          p.setPlayerMode(PlayerMode.lowLatency);
          p.setReleaseMode(ReleaseMode.stop);
          return p;
        });

  void _play(String file, {double rate = 1.0}) {
    final player = _pool[_next];
    _next = (_next + 1) % _pool.length;
    // Fire and forget; a lost sound is better than a frame hitch or a crash.
    Future(() async {
      try {
        await player.stop();
        await player.setPlaybackRate(rate);
        await player.play(AssetSource('audio/$file'));
      } catch (e) {
        debugPrint('GameSfx: could not play $file: $e');
      }
    });
  }

  @override
  void pop({double pitch = 1.0}) {
    // Small extra randomization on top of whatever the caller asked for.
    final jitter = 0.97 + _random.nextDouble() * 0.06;
    _play('pop.wav', rate: (pitch * jitter).clamp(0.5, 2.0));
  }

  @override
  void boom() => _play('boom.wav');

  @override
  void tick() => _play('tick.wav');

  @override
  void go() => _play('go.wav');

  @override
  void fanfare() => _play('fanfare.wav');

  @override
  void whoosh() => _play('whoosh.wav');
}

/// No-op implementation for tests (and any platform without audio).
class SilentGameSfx implements GameSfx {
  const SilentGameSfx();

  @override
  void pop({double pitch = 1.0}) {}
  @override
  void boom() {}
  @override
  void tick() {}
  @override
  void go() {}
  @override
  void fanfare() {}
  @override
  void whoosh() {}
}
