// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNa2DsFYG3xblYmL1lLU1jqt3MxlFtWWg',
    appId: '1:488967944620:web:864da83aae20ea379c2209',
    messagingSenderId: '488967944620',
    projectId: 'taskmaster-app-3d480',
    authDomain: 'taskmaster-app-3d480.firebaseapp.com',
    storageBucket: 'taskmaster-app-3d480.firebasestorage.app',
    measurementId: 'G-XXVE3234WD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYYaQyBi2fKe2bSETJPl91I2bVNZOTm84',
    appId: '1:488967944620:android:66b953a2a16547b19c2209',
    messagingSenderId: '488967944620',
    projectId: 'taskmaster-app-3d480',
    storageBucket: 'taskmaster-app-3d480.firebasestorage.app',
  );

  /// Values copied from ios/Runner/GoogleService-Info.plist (the iOS app
  /// registered in the taskmaster-app-3d480 project). Regenerate with
  /// `flutterfire configure --platforms=ios` if the plist changes.
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSVW23CB3hS0VBUpPat27vlLiWbFEfVp8',
    appId: '1:488967944620:ios:6a647d2b959716c69c2209',
    messagingSenderId: '488967944620',
    projectId: 'taskmaster-app-3d480',
    storageBucket: 'taskmaster-app-3d480.firebasestorage.app',
    iosClientId: '488967944620-lhugdf44nsemgruva1s0p8kkpo2cd6mc.apps.googleusercontent.com',
    iosBundleId: 'com.sagearbor.taskcaster.app',
  );
}
