/// Pure invite-link parsing and building. No plugin imports — everything in
/// this file is unit-testable without platform channels.
///
/// Invite codes are 6 characters drawn from [InviteLinks.codeAlphabet]
/// (no I/L/O/0/1 to avoid transcription mistakes) and are generated by the
/// game data sources; this file only validates/normalizes them.
library;

/// Builds and parses the shareable invite links.
class InviteLinks {
  InviteLinks._();

  /// Characters a valid invite code may contain (matches the generator in the
  /// game data sources).
  static const String codeAlphabet = 'ABCDEFGHJKMNPQRSTUVWXYZ23456789';

  static const int codeLength = 6;

  /// Custom scheme handled by the Android intent-filter: taskcaster://join
  static const String appScheme = 'taskcaster';
  static const String appHost = 'join';

  /// Firebase Hosting domain that serves web/join/index.html.
  static const String webHost = 'taskmaster-app-3d480.web.app';

  static final RegExp _codePattern =
      RegExp('^[$codeAlphabet]{$codeLength}\$');

  /// The canonical shareable join URL for [code]. Served by the static
  /// web/join/index.html landing page, which routes the user into the app
  /// (deep link) or to the Play Store (install referrer).
  ///
  /// When [ref] (the inviter's uid) is supplied it is carried through as a
  /// `ref=` query param, so the joiner can auto-friend the person who invited
  /// them once the join succeeds.
  static String joinUrl(String code, {String? ref}) {
    final base = 'https://$webHost/join/?code=${Uri.encodeQueryComponent(code)}';
    if (ref == null || ref.trim().isEmpty) return base;
    return '$base&ref=${Uri.encodeQueryComponent(ref.trim())}';
  }

  /// True when [code] is exactly [codeLength] characters from [codeAlphabet].
  static bool isValidCode(String code) => _codePattern.hasMatch(code);

  /// Trims/uppercases [raw] and returns it when it is a valid invite code,
  /// otherwise null. Lowercase input is accepted (users retype codes).
  static String? normalizeCode(String? raw) {
    if (raw == null) return null;
    final code = raw.trim().toUpperCase();
    return isValidCode(code) ? code : null;
  }

  /// Extracts an invite code from a deep link.
  ///
  /// Accepted forms:
  /// - taskcaster://join?code=ABC234
  /// - https://taskmaster-app-3d480.web.app/join/?code=ABC234 (future-proofing
  ///   for verified App Links; http is tolerated too)
  ///
  /// Returns null for any other URI or when the code is missing/invalid.
  static String? codeFromUri(Uri uri) {
    final isAppLink = uri.scheme == appScheme && uri.host == appHost;
    final isWebLink = (uri.scheme == 'https' || uri.scheme == 'http') &&
        uri.host == webHost &&
        uri.pathSegments.isNotEmpty &&
        uri.pathSegments.first == appHost;
    if (!isAppLink && !isWebLink) return null;
    return normalizeCode(uri.queryParameters['code']);
  }

  /// Extracts the inviter reference (`ref=`) from a deep link, when present.
  ///
  /// Only returns a value for links this app recognises (same host/scheme
  /// checks as [codeFromUri]) and only when a valid invite code is ALSO present
  /// — a bare `ref` with no code is meaningless. The ref is an opaque uid, so
  /// it is only trimmed (not validated against the code alphabet). Returns null
  /// when absent/blank.
  static String? refFromUri(Uri uri) {
    if (codeFromUri(uri) == null) return null;
    return _cleanRef(uri.queryParameters['ref']);
  }

  /// Extracts the inviter reference (`ref=`) from a Play Install Referrer
  /// string of the form `invite_code=X&ref=Y` (URL-decoded or still-encoded).
  /// Only returns a value when a valid invite code is also present. Returns
  /// null when absent/blank/malformed.
  static String? refFromReferrer(String? referrer) {
    if (referrer == null || referrer.trim().isEmpty) return null;
    if (codeFromReferrer(referrer) == null) return null;

    final candidates = <String>{referrer};
    try {
      candidates.add(Uri.decodeComponent(referrer));
    } on ArgumentError {
      // Malformed percent-encoding — the raw pass still runs.
    }

    for (final candidate in candidates) {
      Map<String, String> params;
      try {
        params = Uri.splitQueryString(candidate);
      } on ArgumentError {
        continue;
      }
      final ref = _cleanRef(params['ref']);
      if (ref != null) return ref;
    }
    return null;
  }

  static String? _cleanRef(String? raw) {
    if (raw == null) return null;
    final ref = raw.trim();
    return ref.isEmpty ? null : ref;
  }

  /// Extracts an invite code from a Play Install Referrer string.
  ///
  /// Play delivers the `referrer=` query parameter of the store URL, usually
  /// already URL-decoded (`invite_code=ABC234`, possibly alongside utm_*
  /// params) but occasionally still encoded (`invite_code%3DABC234`) — both
  /// forms are handled. Returns null when absent or invalid.
  static String? codeFromReferrer(String? referrer) {
    if (referrer == null || referrer.trim().isEmpty) return null;

    // Try the raw string first, then a defensively-decoded copy.
    final candidates = <String>{referrer};
    try {
      candidates.add(Uri.decodeComponent(referrer));
    } on ArgumentError {
      // Malformed percent-encoding — the raw pass still runs.
    }

    for (final candidate in candidates) {
      Map<String, String> params;
      try {
        params = Uri.splitQueryString(candidate);
      } on ArgumentError {
        continue;
      }
      final code = normalizeCode(params['invite_code']);
      if (code != null) return code;
    }
    return null;
  }
}
