import 'package:equatable/equatable.dart';

/// What kind of thing the player handed in.
///
/// [link] is the legacy (and still supported) "paste a video URL" path and is
/// the default, so every submission serialized before this field existed
/// deserializes unchanged.
///
/// [video] is an in-app clip: recorded by the player, uploaded to Firebase
/// Storage under `submissions/{uid}/{yyyyMMdd}/{slot}` and played back from
/// its download URL. It reuses [videoUrl] for that URL — the media type, not
/// the field, is what distinguishes it from a pasted [link].
enum SubmissionMediaType { link, photo, text, video }

class Submission extends Equatable {
  final String id;
  final String userId;
  final String? videoUrl;
  final String? textAnswer;
  final int score;
  final bool isJudged;
  final DateTime submittedAt;

  /// What was handed in. Defaults to [SubmissionMediaType.link].
  final SubmissionMediaType mediaType;

  /// The body of a text entry (wordplay tasks). Distinct from the legacy
  /// [textAnswer], which is the puzzle-answer field.
  final String? text;

  /// AUTO-generated by `AutoEdit.caption` — the twist plus the player's
  /// timing. A player may later append a single "word for the judge"; there is
  /// never a caption-writing step in the submission flow.
  final String? caption;

  /// AUTO-chosen by `AutoEdit.stamp` from `Stamps.values`. Never supplied by
  /// the UI.
  final String? stamp;

  /// True when the player submitted after `durationSeconds + 30 s` of grace.
  final bool isLate;

  /// `submittedAt - startedAt` in seconds; null when the player never tapped
  /// Start (so there is no clock to measure against).
  final int? elapsedSeconds;

  /// The Arena `feed_posts` document id when this submission was shared.
  final String? feedPostId;

  /// In-app clip only: the bucket object path
  /// (`submissions/{uid}/{yyyyMMdd}/{slot}`) the clip was written to. Null for
  /// every other medium.
  final String? videoStoragePath;

  /// In-app clip only: the uploaded size in bytes (<= `VideoPolicy
  /// .maxUploadBytes`).
  final int? videoBytes;

  /// In-app clip only: the MIME type actually uploaded (`video/mp4`,
  /// `video/quicktime`, `video/webm`).
  final String? videoContentType;

  /// In-app clip only: the clip's duration in seconds, or null when the
  /// recorder did not tell us (playback trims at the cap either way).
  final double? videoDurationSeconds;

  /// In-app clip only: seconds already burned on the TASK clock (since
  /// `startedAt`) when the recorder opened. Playback draws the task countdown
  /// from `timerSeconds - clockOffsetSeconds - position`, and a later
  /// server-side splice can rebuild the same clock without OCR.
  final int? clockOffsetSeconds;

  /// The task's `durationSeconds` at submit time, carried on the submission so
  /// the countdown can be drawn from the post alone.
  final int? timerSeconds;

  const Submission({
    required this.id,
    required this.userId,
    this.videoUrl,
    this.textAnswer,
    required this.score,
    required this.isJudged,
    required this.submittedAt,
    this.mediaType = SubmissionMediaType.link,
    this.text,
    this.caption,
    this.stamp,
    this.isLate = false,
    this.elapsedSeconds,
    this.feedPostId,
    this.videoStoragePath,
    this.videoBytes,
    this.videoContentType,
    this.videoDurationSeconds,
    this.clockOffsetSeconds,
    this.timerSeconds,
  });

  factory Submission.fromMap(Map<String, dynamic> map) {
    return Submission(
      id: map['id'] as String,
      userId: map['userId'] as String,
      videoUrl: map['videoUrl'] as String?,
      textAnswer: map['textAnswer'] as String?,
      score: map['score'] as int? ?? 0,
      isJudged: map['isJudged'] as bool? ?? false,
      submittedAt: DateTime.parse(map['submittedAt'] as String),
      // Backward-compatible: rows written before the Arena existed have no
      // mediaType key and parse as the legacy video-link submission.
      mediaType: SubmissionMediaType.values.firstWhere(
        (e) => e.name == map['mediaType'],
        orElse: () => SubmissionMediaType.link,
      ),
      text: map['text'] as String?,
      caption: map['caption'] as String?,
      stamp: map['stamp'] as String?,
      isLate: map['isLate'] as bool? ?? false,
      elapsedSeconds: map['elapsedSeconds'] as int?,
      feedPostId: map['feedPostId'] as String?,
      // Absent on every document written before in-app video existed.
      videoStoragePath: map['videoStoragePath'] as String?,
      videoBytes: map['videoBytes'] as int?,
      videoContentType: map['videoContentType'] as String?,
      videoDurationSeconds: (map['videoDurationSeconds'] as num?)?.toDouble(),
      clockOffsetSeconds: map['clockOffsetSeconds'] as int?,
      timerSeconds: map['timerSeconds'] as int?,
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'userId': userId,
      'videoUrl': videoUrl,
      'textAnswer': textAnswer,
      'score': score,
      'isJudged': isJudged,
      'submittedAt': submittedAt.toIso8601String(),
      'mediaType': mediaType.name,
      'text': text,
      'caption': caption,
      'stamp': stamp,
      'isLate': isLate,
      'elapsedSeconds': elapsedSeconds,
      'feedPostId': feedPostId,
      'videoStoragePath': videoStoragePath,
      'videoBytes': videoBytes,
      'videoContentType': videoContentType,
      'videoDurationSeconds': videoDurationSeconds,
      'clockOffsetSeconds': clockOffsetSeconds,
      'timerSeconds': timerSeconds,
    };
  }

  Submission copyWith({
    String? id,
    String? userId,
    String? videoUrl,
    String? textAnswer,
    int? score,
    bool? isJudged,
    DateTime? submittedAt,
    SubmissionMediaType? mediaType,
    String? text,
    String? caption,
    String? stamp,
    bool? isLate,
    int? elapsedSeconds,
    String? feedPostId,
    String? videoStoragePath,
    int? videoBytes,
    String? videoContentType,
    double? videoDurationSeconds,
    int? clockOffsetSeconds,
    int? timerSeconds,
  }) {
    return Submission(
      id: id ?? this.id,
      userId: userId ?? this.userId,
      videoUrl: videoUrl ?? this.videoUrl,
      textAnswer: textAnswer ?? this.textAnswer,
      score: score ?? this.score,
      isJudged: isJudged ?? this.isJudged,
      submittedAt: submittedAt ?? this.submittedAt,
      mediaType: mediaType ?? this.mediaType,
      text: text ?? this.text,
      caption: caption ?? this.caption,
      stamp: stamp ?? this.stamp,
      isLate: isLate ?? this.isLate,
      elapsedSeconds: elapsedSeconds ?? this.elapsedSeconds,
      feedPostId: feedPostId ?? this.feedPostId,
      videoStoragePath: videoStoragePath ?? this.videoStoragePath,
      videoBytes: videoBytes ?? this.videoBytes,
      videoContentType: videoContentType ?? this.videoContentType,
      videoDurationSeconds:
          videoDurationSeconds ?? this.videoDurationSeconds,
      clockOffsetSeconds: clockOffsetSeconds ?? this.clockOffsetSeconds,
      timerSeconds: timerSeconds ?? this.timerSeconds,
    );
  }

  bool get hasVideoUrl => videoUrl != null && videoUrl!.isNotEmpty;
  bool get hasTextAnswer => textAnswer != null && textAnswer!.isNotEmpty;

  @override
  List<Object?> get props => [
        id,
        userId,
        videoUrl,
        textAnswer,
        score,
        isJudged,
        submittedAt,
        mediaType,
        text,
        caption,
        stamp,
        isLate,
        elapsedSeconds,
        feedPostId,
        videoStoragePath,
        videoBytes,
        videoContentType,
        videoDurationSeconds,
        clockOffsetSeconds,
        timerSeconds,
      ];
}
